/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'selector',
  content: ["./Components/**/*.{razor,html,cshtml}"],
  theme: {
      extend: {
          fontFamily: {
              sans: ['Inter', 'sans-serif'],
          },
      },
      colors: {
          pBackground: "#fff",
          sBackground: "#fdfdfd",
          tBackground: "#f4f5f6", 
          qBackground: "#0e0f0f",
          primary: "#0e0f0f",
          pText: "#0e0f0f",
          sText: "#41444b",
          tText: "#475367",
          qText: "#fff",
          success: "#0F973D",
          warning: "#be9a37",
          danger: "#F31260",
          neutral: "#bbbbbb",
          link: "#006FEE",
          border: "#e7e9ec",
          white: "#fff",
          black: "#000000",
          dpBackground: "#1f1f1f",
          dsBackground: "#272727",
          dtBackground: "#343434",
          dprimary: "#0e0f0f",
          dpText: "#0e0f0f",
          dsText: "#41444b",
          dttext: "#475367",
      },
      fontWeight: {
          normal: '400',
          medium: '500',
          semibold: '600',
          bold: '700',
      },
  },
  plugins: [],
}